### ISSUE TITLE
Renaming of variables -- Non alphanumeric characters

### ISSUE THREAD

**Issue by ploc** [coco-team/cocoSim#1]
When block or subsystems names contains non alphanumeric character the generated lustre file is not usable. Recall that lustrec lexer rule for identifier is ['_' 'a'-'z'] [ '_' 'a'-'z' 'A'-'Z' '0'-'9']*
In the current version, parenthesis are renamed as lpar rpar, but comma ',', plus '+' are preserved.
They should be encoded as well as strings.

**Comment by hbourbouh** [comment]
solved by replacing all characters that does not respect lustre rule by a dash
